source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoachKit_Example', :exclusive => true do
  pod "CoachKit", :path => "../"
end

target 'CoachKit_Tests', :exclusive => true do
  pod "CoachKit", :path => "../"

  
end
